/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.learning.gui;

import java.sql.Date;
import javax.swing.JOptionPane;
import vn.learning.dao.TheNopTienDAO;
import vn.learning.dao.TheNopTienDAOImpl;
import vn.learning.model.TheNopTien;

/**
 *
 * @author Admin
 */
public class TheNopTienGUI extends javax.swing.JPanel {

    private TheNopTienDAO theNopTienDAO;
    private Integer id;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    private void fillDataToTable() {
        tblTheNopTien.setModel(new TheNopTienTableModel());
        tblTheNopTien.repaint();
        tblTheNopTien.revalidate();
    }

    private void emptyControl() {
        txfSoSeri.setText("");
        txfMenhGia.setText("");
        dateChooseThoiGianNop.setDate(null);
        cbTrangThai.setSelected(false);
    }

    /**
     * Creates new form TheNop
     */
    public TheNopTienGUI() {
        initComponents();
        fillDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTheNopTien = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfSoSeri = new javax.swing.JTextField();
        txfMenhGia = new javax.swing.JTextField();
        dateChooseThoiGianNop = new com.toedter.calendar.JDateChooser();
        cbTrangThai = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new java.awt.BorderLayout());

        tblTheNopTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTheNopTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTheNopTienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTheNopTien);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Số Seri");

        jLabel2.setText("Mệnh giá");

        jLabel3.setText("Thời gian nộp");

        jLabel4.setText("Trạng thái");

        dateChooseThoiGianNop.setDateFormatString("MM/dd/ yyyy");

        cbTrangThai.setText("Đã nộp tiền");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfMenhGia)
                    .addComponent(txfSoSeri, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooseThoiGianNop, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTrangThai))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txfMenhGia, txfSoSeri});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfSoSeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfMenhGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(dateChooseThoiGianNop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cbTrangThai)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jPanel2.add(jPanel3, java.awt.BorderLayout.WEST);

        jButton1.setText("Thêm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jButton2.setText("Thay đổi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jPanel2.add(jPanel4, java.awt.BorderLayout.EAST);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void tblTheNopTienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTheNopTienMouseClicked
        Integer row = tblTheNopTien.getSelectedRow();
        setId((Integer) tblTheNopTien.getModel().getValueAt(row, 0));

        String soSeri = (String) tblTheNopTien.getModel().getValueAt(row, 1);
        Integer menhGia = (Integer) tblTheNopTien.getModel().getValueAt(row, 2);
        Boolean kiemTra = (Boolean) tblTheNopTien.getModel().getValueAt(row, 4);

        txfSoSeri.setText(soSeri);
        txfMenhGia.setText(menhGia.toString());
        if (kiemTra == true) {
            cbTrangThai.setSelected(true);
        } else {
            cbTrangThai.setSelected(false);
        }

        java.util.Date thoiGianNop = new java.util.Date();

        thoiGianNop = (java.util.Date) tblTheNopTien.getModel().getValueAt(row, 3);

        dateChooseThoiGianNop.setDate(thoiGianNop);

    }//GEN-LAST:event_tblTheNopTienMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (id == null || id < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để thực hiện delete!");
        } else {
            theNopTienDAO = new TheNopTienDAOImpl();
            theNopTienDAO.deleteTheNop(id);
            JOptionPane.showMessageDialog(null, "Delete thành công!");
            fillDataToTable();
            emptyControl();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String soSeri = txfSoSeri.getText();
            Integer menhGia = Integer.valueOf(txfMenhGia.getText());
            java.util.Date date = dateChooseThoiGianNop.getDate();
            java.sql.Date thoiGianNop;
            if (date == null) {
                thoiGianNop = null;
            } else {
                thoiGianNop = new java.sql.Date(date.getTime());
            }

            Boolean trangThai = cbTrangThai.isSelected();

            TheNopTien theNopTien = new TheNopTien();
            theNopTien.setSoSeri(soSeri);
            theNopTien.setMenhGia(menhGia);
            theNopTien.setThoiGianNop(thoiGianNop);
            theNopTien.setTrangThai(trangThai);

            theNopTienDAO = new TheNopTienDAOImpl();
            theNopTienDAO.addTheNop(theNopTien);

            JOptionPane.showMessageDialog(null, "Đã thêm vào thành công!");

            fillDataToTable();
            emptyControl();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số nguyên dương vào mục Mệnh giá!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (id == null || id < 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để thực hiện update!");
            } else {
                theNopTienDAO = new TheNopTienDAOImpl();
                TheNopTien theNopTien = new TheNopTien();
                theNopTien.setId(id);
                theNopTien.setSoSeri(txfSoSeri.getText());
                theNopTien.setMenhGia(Integer.valueOf(txfMenhGia.getText()));
                theNopTien.setTrangThai(Boolean.valueOf(cbTrangThai.isSelected()));

                java.util.Date date = dateChooseThoiGianNop.getDate();
                java.sql.Date thoiGianNop;
                if (date == null) {
                    thoiGianNop = null;
                } else {
                    thoiGianNop = new java.sql.Date(date.getTime());
                }
                theNopTien.setThoiGianNop(thoiGianNop);

                theNopTienDAO.updateTheNop(theNopTien);

                JOptionPane.showMessageDialog(null, "Cập nhật thành công!");
                fillDataToTable();
                emptyControl();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập vào số nguyên dương ở mục thẻ nộp tiền!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        emptyControl();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbTrangThai;
    private com.toedter.calendar.JDateChooser dateChooseThoiGianNop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTheNopTien;
    private javax.swing.JTextField txfMenhGia;
    private javax.swing.JTextField txfSoSeri;
    // End of variables declaration//GEN-END:variables
}
